name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          backstage_base_url: https://demo.backstage.io

      - name: Print Output
        id: output
        run: |-
          echo "${{ steps.test-action.outputs.count }}"
          echo "${{ steps.test-action.outputs.entities_json }}"
          echo "${{ steps.test-action.outputs.entity_refs_json }}"
          echo "${{ steps.test-action.outputs.entity_names_json }}"
          echo "${{ steps.test-action.outputs.first_entity_json }}"
          echo "${{ steps.test-action.outputs.has_results }}"
          echo "${{ steps.test-action.outputs.raw_response_json }}"
